# Generated by Django 4.1 on 2022-08-10 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ErrModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lang_name', models.CharField(max_length=240)),
                ('err_title', models.CharField(max_length=240)),
                ('fixer_code', models.CharField(max_length=3000)),
                ('os_tech', models.CharField(max_length=240)),
            ],
        ),
    ]
