# Generated by Django 4.1 on 2022-12-03 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usarios', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='errmodel',
            name='err_title',
            field=models.CharField(max_length=240),
        ),
        migrations.AlterField(
            model_name='errmodel',
            name='fixer_code',
            field=models.CharField(max_length=3000),
        ),
    ]
