# Generated by Django 4.0.4 on 2022-08-10 23:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usarios', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='errmodel',
            table='errmodel',
        ),
    ]
